# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: toolri

channels:
  - conda-forge

dependencies:
  - python
  - make
  - pyinstaller
  - python-build
  - twine
  - pip:
    - -r requirements.txt
